Add missing include
wrapper.c: In function 'is_smd_device':
wrapper.c:69:58: error: implicit declaration of function 'major' [-Werror=implicit-function-declaration]
   69 |  if (snprintf(path, sizeof(path), /sys/dev/char/%d:%d, major(stat.st_rdev), minor(stat.st_rdev)) < 0) {
      |                                                          ^~~~~
wrapper.c:69:79: error: implicit declaration of function 'minor' [-Werror=implicit-function-declaration]
   69 |  (snprintf(path, sizeof(path), /sys/dev/char/%d:%d, major(stat.st_rdev), minor(stat.st_rdev)) < 0) {
      |                                                                            ^~~~~